import Foundation
import Testing
@testable import KoeCore

@Suite("PasteboardMarkers")
struct PasteboardMarkersTests {
    @Test("marker type identifiers follow the nspasteboard convention")
    func markerTypes() {
        #expect(PasteboardMarkers.transient == "org.nspasteboard.TransientType")
        #expect(PasteboardMarkers.autoGenerated == "org.nspasteboard.AutoGeneratedType")
        #expect(PasteboardMarkers.source == "org.nspasteboard.source")
    }

    @Test("session type embeds the UUID under our namespace")
    func sessionType() {
        let id = UUID()
        let type = PasteboardMarkers.sessionType(id)
        #expect(type.hasPrefix(PasteboardMarkers.sessionTypePrefix + "."))
        #expect(type.contains(id.uuidString))
    }

    @Test("distinct sessions get distinct marker types")
    func sessionTypeUnique() {
        #expect(PasteboardMarkers.sessionType(UUID()) != PasteboardMarkers.sessionType(UUID()))
    }
}

@Suite("PasteTextPreparer")
struct PasteTextPreparerTests {
    @Test("non-terminal target is left untouched, no newline warning")
    func nonTerminalUntouched() {
        let p = PasteTextPreparer.prepare("line one\nline two\n", targetBundleID: "com.tinyspeck.slackmacgap")
        #expect(p.text == "line one\nline two\n")
        #expect(p.warnNewlines == false)
    }

    @Test("nil bundle id is not a terminal")
    func nilBundle() {
        #expect(PasteTextPreparer.isTerminal(bundleID: nil) == false)
        let p = PasteTextPreparer.prepare("echo hi\n", targetBundleID: nil)
        #expect(p.text == "echo hi\n")
        #expect(p.warnNewlines == false)
    }

    @Test("Terminal.app strips a single trailing newline, no interior warning")
    func terminalSingleTrailing() {
        let p = PasteTextPreparer.prepare("echo hi\n", targetBundleID: "com.apple.Terminal")
        #expect(p.text == "echo hi")
        #expect(p.warnNewlines == false)
    }

    @Test("terminal strips all trailing newlines and carriage returns")
    func terminalMultipleTrailing() {
        let p = PasteTextPreparer.prepare("ls\r\n\n", targetBundleID: "com.googlecode.iterm2")
        #expect(p.text == "ls")
        #expect(p.warnNewlines == false)
    }

    @Test("terminal warns when an interior line break survives stripping")
    func terminalInteriorWarns() {
        let p = PasteTextPreparer.prepare("cmd one\ncmd two\n", targetBundleID: "com.apple.Terminal")
        #expect(p.text == "cmd one\ncmd two")
        #expect(p.warnNewlines == true)
    }

    @Test("terminal payload of only newlines becomes empty without warning")
    func terminalOnlyNewlines() {
        let p = PasteTextPreparer.prepare("\n\n", targetBundleID: "com.apple.Terminal")
        #expect(p.text == "")
        #expect(p.warnNewlines == false)
    }

    @Test("no-newline terminal payload is unchanged")
    func terminalNoNewline() {
        let p = PasteTextPreparer.prepare("git status", targetBundleID: "com.mitchellh.ghostty")
        #expect(p.text == "git status")
        #expect(p.warnNewlines == false)
    }
}

@Suite("PasteVerification")
struct PasteVerificationTests {
    @Test("unreadable AX (nil) is unverifiable — assume success")
    func nilUnverifiable() {
        #expect(PasteVerification.verdict(focusedValue: nil, insertedTail: "hello") == .unverifiable)
    }

    @Test("empty tail is unverifiable")
    func emptyTail() {
        #expect(PasteVerification.verdict(focusedValue: "anything", insertedTail: "") == .unverifiable)
    }

    @Test("tail present in focus verifies insertion")
    func tailPresent() {
        #expect(PasteVerification.verdict(focusedValue: "greeting: hello world", insertedTail: "hello world") == .verifiedInserted)
    }

    @Test("readable focus lacking the tail is an explicit failure")
    func tailAbsent() {
        #expect(PasteVerification.verdict(focusedValue: "unrelated content", insertedTail: "hello world") == .verifiedFailed)
    }
}
