import Foundation

/// Pasteboard marker types written alongside the payload during paste
/// simulation (Design §6.3-3, §9). These follow the nspasteboard.org
/// convention so passive clipboard-history tools (Maccy, Alfred, Pastebot,
/// 1Password) skip recording our transient write; receiving apps ignore them.
///
/// `ConcealedType` is deliberately NOT written — its "sensitive like a
/// password" semantics are stronger than needed, and `TransientType` already
/// defeats history tools.
public enum PasteboardMarkers {
    /// History tools must not record this write.
    public static let transient = "org.nspasteboard.TransientType"
    /// The write was produced by software, not a human copy.
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// Bundle id of the producing app (value = our bundle id).
    public static let source = "org.nspasteboard.source"

    /// Namespace for the private per-paste UUID marker used to detect whether
    /// another process replaced the clipboard before we restore the snapshot.
    public static let sessionTypePrefix = "dev.newt.Koe.paste-session"

    /// The private marker type carrying this paste's session UUID. Its presence
    /// on restore proves our write is still the current clipboard content; if
    /// it is gone, another process wrote in the meantime and restoring the
    /// snapshot would clobber their content (Design §6.3-6).
    public static func sessionType(_ id: UUID) -> String {
        "\(sessionTypePrefix).\(id.uuidString)"
    }
}

/// The payload text to place on the clipboard, plus whether the HUD should warn
/// about embedded line breaks (terminal-family targets only).
public struct PastePreparation: Sendable, Equatable {
    /// Text to write to the pasteboard (trailing newlines stripped for
    /// terminals; unchanged otherwise).
    public let text: String
    /// True when a terminal target still contains an interior line break after
    /// trailing-newline stripping — pasting it may run partial commands, so the
    /// HUD cautions the user (Design §6.5 terminal rule).
    public let warnNewlines: Bool

    public init(text: String, warnNewlines: Bool) {
        self.text = text
        self.warnNewlines = warnNewlines
    }
}

/// Pure text preparation for paste simulation: terminal-family detection and
/// the trailing-newline stripping rule (Design §5.2 app-context, §6.5).
///
/// Terminals (Terminal.app, iTerm2, and other CLIs) execute a command the
/// moment a trailing newline is pasted, so we strip trailing newlines and warn
/// when interior line breaks remain. Bracketed-paste terminals handle the rest
/// safely as a normal paste.
public enum PasteTextPreparer {
    /// Foreground bundle ids treated as terminal-family. Matched exactly; an
    /// unknown terminal simply pastes as-is (the newline risk is real but rare,
    /// and per-app overrides in M5-T3 cover stragglers).
    public static let terminalBundleIDs: Set<String> = [
        "com.apple.Terminal",
        "com.googlecode.iterm2",
        "com.github.wez.wezterm",
        "net.kovidgoyal.kitty",
        "org.alacritty",
        "com.mitchellh.ghostty",
        "dev.warp.Warp-Stable",
        "co.zeit.hyper",
        "org.tabby",
    ]

    public static func isTerminal(bundleID: String?) -> Bool {
        guard let bundleID else { return false }
        return terminalBundleIDs.contains(bundleID)
    }

    /// Prepare `text` for the given target. Non-terminal targets are untouched;
    /// terminals get trailing newlines/carriage-returns stripped and a warning
    /// flag when interior breaks remain.
    public static func prepare(_ text: String, targetBundleID: String?) -> PastePreparation {
        guard isTerminal(bundleID: targetBundleID) else {
            return PastePreparation(text: text, warnNewlines: false)
        }
        // `isNewline` matches \n, \r, and the combined \r\n grapheme cluster
        // (Swift treats CRLF as one Character), plus other Unicode line breaks.
        var stripped = Substring(text)
        while let last = stripped.last, last.isNewline {
            stripped = stripped.dropLast()
        }
        let result = String(stripped)
        let warn = result.contains(where: \.isNewline)
        return PastePreparation(text: result, warnNewlines: warn)
    }
}

/// Best-effort verdict on whether a paste landed, from an Accessibility read of
/// the focused element (Design §6.3-5). AX reads are optional: when the element
/// is unreadable we assume success rather than pay latency chasing a rare
/// failure. Only an explicitly observed mismatch (`verifiedFailed`) escalates to
/// the next fallback path (M5-T3).
public enum PasteVerification {
    public enum Verdict: Sendable, Equatable {
        /// The inserted tail was found near the focus — treat as success.
        case verifiedInserted
        /// The focus was readable and clearly lacks the inserted tail — the
        /// only case that escalates to path 2.
        case verifiedFailed
        /// AX unreadable (or nothing to check) — assume success, don't escalate.
        case unverifiable
    }

    /// Decide from a post-paste focus read. `focusedValue` is the concatenated
    /// `AXValue`/`AXSelectedText` vicinity (nil when AX is unreadable);
    /// `insertedTail` is the trailing slice of the pasted text we look for.
    public static func verdict(focusedValue: String?, insertedTail: String) -> Verdict {
        guard let focusedValue else { return .unverifiable }
        // An empty tail (e.g. an all-newline terminal payload) gives us nothing
        // to match on — don't manufacture a failure.
        guard !insertedTail.isEmpty else { return .unverifiable }
        return focusedValue.contains(insertedTail) ? .verifiedInserted : .verifiedFailed
    }
}
